version: '3.8'


services:
  es01:
    container_name: es01
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      node.name: es01
      ELASTIC_PASSWORD: changeme
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  ls01:
    container_name: ls01
    restart: always
    image: docker.elastic.co/logstash/logstash:7.8.0
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/config/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./logstash/pipelines:/usr/share/logstash/pipeline
    command: "logstash"
    ports:
      - "5044:5044"
      - "9600:9600"
    networks:
      - elk
    depends_on:
      - es01
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9600 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  kb01:
    container_name: kb01
    restart: always
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - es01
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:5601/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  fb01:
    container_name: fb01
    restart: always
    image: docker.elastic.co/beats/filebeat:7.8.0
    environment:
      STRICT_PERMS: "false"
    volumes:
      - ./logs/:/data/latam/logs
      - ./filebeat/filebeat_apache.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk
    depends_on:
      - ls01
      - es01
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://ls01:9600 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  flog01:
    container_name: flog01
    restart: always
    image: mingrammer/flog:0.4.2
    volumes:
      - ./assets/logs:/logs
    depends_on:
      - es01
      - ls01
      - fb01
    command: -l -d 1 -f apache_common -t log -w -o /logs/apache.log

networks:
  elk:
