  - pipeline.id: beats
    config.string: |
      input { beats { port => 5044 } }
      output {
          if [log_type] =~ "apache" {
            pipeline { send_to => apache_address }
          }
          else {
            elasticsearch {
            index => "all-%{+YYYY.MM.dd}"
            hosts => ["es01:9200"]
            user => "elastic"
            password => "changeme"
            ssl => false
            ssl_certificate_verification => false
            }
          }
      }

  - pipeline.id: apache
    path.config: "/usr/share/logstash/pipeline/apache.conf"